apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: argo-cmp-timoni
          image: 35.200.235.204/creative-studio/timoni-cmp@sha256:bb49904361a67c726bab4dc969f7eb592f3e5fe9bacc9faffdd5ca72ec2e2a65
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /tmp
              name: cmp-tmp
      volumes:
        - name: cmp-tmp
          emptyDir: {}
