apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: argo-cmp-timoni
          image: 35.200.235.204/creative-studio/timoni-cmp@sha256:922b3b64b9c0942a953950d3d3be36ab414b79395f5f3fbea70f2e827a7008bf
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /tmp
              name: cmp-tmp
      volumes:
        - name: cmp-tmp
          emptyDir: {}
