# argocd/parent-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: creative-studio-parent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/DenisRuparel/Timoni-implementation-with-ArgoCD-Plugin---DevOps.git
      targetRevision: main
      path: argocd-install
    - repoURL: https://github.com/DenisRuparel/Timoni-implementation-with-ArgoCD-Plugin---DevOps.git
      targetRevision: main
      path: argocd/apps
  destination:
    server: https://192.168.56.107:6443
    namespace: argocd
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: argocd-repo-server
      namespace: argocd
      jsonPointers:
        - /spec/template/spec/containers
        - /spec/template/spec/initContainers
        - /spec/template/spec/volumes
        - /spec/template/spec/imagePullSecrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true             # ✅ critical
