apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: creative-studio-parent
  namespace: argocd
spec:
  project: creative-studio

  source:
    repoURL: https://github.com/DenisRuparel/Timoni-implementation-with-ArgoCD-Plugin---DevOps
    targetRevision: main
    path: argocd/apps

  destination:
    server: https://10.160.0.4:6443
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
