apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: creative-studio-beta
  namespace: argocd
spec:
  project: creative-studio

  source:
    repoURL: https://github.com/DenisRuparel/Timoni-implementation-with-ArgoCD-Plugin---DevOps
    targetRevision: main
    path: .

    plugin:
      name: argo-cmp-timoni
      env:
        - name: ARGOCD_ENV
          value: beta

  destination:
    server: https://35.200.235.204:6443
    namespace: creative-studio-beta

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
