apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: creative-studio-stage
  namespace: argocd
spec:
  project: creative-studio

  source:
    repoURL: https://github.com/DenisRuparel/Timoni-implementation-with-ArgoCD-Plugin---DevOps
    targetRevision: main
    path: .

    plugin:
      name: timoni
      env:
        - name: ARGOCD_ENV
          value: stage

  destination:
    server: https://192.168.56.107:6443
    namespace: creative-studio-stage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
     syncOptions:
      - CreateNamespace=true
