apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: creative-studio-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DenisRuparel/Timoni-implementation-with-ArgoCD-Plugin---DevOps.git
    targetRevision: main
    path: environments/stage
    plugin:
      name: timoni-v1.0
  destination:
    server: https://192.168.56.107:6443
    namespace: creative-studio-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
